### ISSUE TITLE
no project file

### ISSUE THREAD

**Issue by ianmckenna87** [UtMan88/Godot3DFlightControls#1]
there is no project file in the package

**Comment by UtMan88** [comment]
Can you explain? The project.godot file can be found in the root of the repo here: https://github.com/UtMan88/Godot3DFlightControls/blob/main/project.godot

**Comment by ianmckenna87** [comment]
![image](https://github.com/UtMan88/Godot3DFlightControls/assets/132845829/b99f6266-8a98-417b-b495-b88a601eb005)
this is all that appears in the project folder when downloading from the asset library

**Comment by UtMan88** [comment]
The heck!? I'll get to the bottom of this.

**Comment by UtMan88** [comment]
Just submitted an update to the Asset Library. Will let you know when it gets approved!

**Comment by UtMan88** [comment]
OK! Seems to load up fine now! Thanks for the issue!

**Comment by ianmckenna87** [comment]
No worries, thanks for the awesome and interesting project! Keeping an eye on this one!
